import org.code.neighborhood.*;

public class NeighborhoodRunner {
  public static void main(String[] args) {

 PixelPainter pixel = new PixelPainter();
    
pixel.paintBackground("pink",16);
pixel.resetPosition();
pixel.paintRow1();
pixel.paintRow2();
pixel.paintRow3();
pixel.paintRow4();
pixel.paintRow5();
pixel.paintRow6();
pixel.paintRow7();
pixel.paintRow8();
pixel.paintRow9();
pixel.paintRow10();
pixel.paintRow11();
pixel.paintRow12();
pixel.paintRow13();
pixel.paintRow14();
pixel.paintRow15();
  }
}
